apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: keycloak.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Keycloak custom operator to support Realms and Client
  displayName: Keycloak
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - keycloak
  - identity
  - authentication
  links:
  - name: Keycloak
    url: https://keycloak.domain
  maturity: alpha
  provider:
    name: Theseus Org
    url: theseus.org.in
  version: 0.0.0
