apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cf-issuer
spec:
  acme:
    email: test@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cf-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-key
            key: api-token
